# Generated by Django 5.1.3 on 2024-11-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
